DROP TABLE IF EXISTS SCAN_TASK;
DROP TABLE IF EXISTS SCAN_EXPORTER;
DROP TABLE IF EXISTS SCAN_IMPORTER;
DROP TABLE IF EXISTS SCAN_DS;

CREATE TABLE
    SCAN_DS
    (
        ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编码',
        DS_NAME VARCHAR(20) NOT NULL COMMENT '扫描数据源名称',
        DS_TYPE VARCHAR(6) NOT NULL COMMENT '扫描数据源类型',
        DESCRIPTION VARCHAR(100) COMMENT '扫描数据源描述',
        PROPS VARCHAR(100) NOT NULL COMMENT '扫描数据源附加属性，为兼容多种数据源',
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID)
    ) COMMENT '扫描数据源' 
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

CREATE TABLE
    SCAN_IMPORTER
    (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        IMP_NAME VARCHAR(20) NOT NULL,
        DESCRIPTION VARCHAR(100),
        PROPS VARCHAR(100) NOT NULL,
        DS_ID BIGINT NOT NULL,
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID),
        CONSTRAINT SCAN_IMPORTER_FK1 FOREIGN KEY (DS_ID) REFERENCES SCAN_DS (ID) ON
    DELETE
        CASCADE
    ON
    UPDATE
        NO ACTION
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

CREATE TABLE
    SCAN_EXPORTER
    (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        EXP_NAME VARCHAR(20) NOT NULL,
        DESCRIPTION VARCHAR(100),
        PROPS VARCHAR(100) NOT NULL,
        DS_ID BIGINT NOT NULL,
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID),
        CONSTRAINT SCAN_EXPORTER_FK1 FOREIGN KEY (DS_ID) REFERENCES SCAN_DS (ID) ON
    DELETE
        CASCADE
    ON
    UPDATE
        NO ACTION
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

CREATE TABLE
    SCAN_TASK
    (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        TASK_NAME VARCHAR(20) NOT NULL,
        TASK_GROUP VARCHAR(20) NOT NULL,
        TASK_TYPE VARCHAR(6) NOT NULL,
        DESCRIPTION VARCHAR(100),
        FETCH_SIZE INT NOT NULL,
        SLEEP_TIME INT NOT NULL,
        POOL_SIZE INT,
        IMP_ID BIGINT NOT NULL,
        EXP_ID BIGINT NOT NULL,
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID),
        CONSTRAINT SCAN_TASK_FK1 FOREIGN KEY (IMP_ID) REFERENCES SCAN_IMPORTER (ID) ON
    DELETE
        RESTRICT
    ON
    UPDATE
        NO ACTION,
        CONSTRAINT SCAN_TASK_FK2 FOREIGN KEY (EXP_ID) REFERENCES SCAN_EXPORTER (ID)
    ON
    DELETE
        RESTRICT
    ON
    UPDATE
        NO ACTION
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    