DROP TABLE IF EXISTS SCAN_TASK;
DROP TABLE IF EXISTS SCAN_EXPORTER;
DROP TABLE IF EXISTS SCAN_IMPORTER;
DROP TABLE IF EXISTS SCAN_DS;

CREATE TABLE
    SCAN_DS
    (
        ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编码',
        DS_NAME VARCHAR(20) NOT NULL COMMENT '扫描数据源名称',
        DS_TYPE VARCHAR(6) NOT NULL COMMENT '扫描数据源类型',
        DESCRIPTION VARCHAR(100) COMMENT '扫描数据源描述',
        PROPS VARCHAR(300) NOT NULL COMMENT '扫描数据源附加属性，为兼容多种数据源',
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID)
    ) COMMENT '扫描数据源' 
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

CREATE TABLE
    SCAN_IMPORTER
    (
        ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编码',
        IMP_NAME VARCHAR(20) NOT NULL COMMENT '导入名称',
        DESCRIPTION VARCHAR(100) COMMENT '导入描述',
        PROPS VARCHAR(300) NOT NULL COMMENT '扫描数据源附加属性，为兼容多种数据源',
        DS_ID BIGINT NOT NULL COMMENT '数据源',
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID),
        CONSTRAINT SCAN_IMPORTER_FK1 FOREIGN KEY (DS_ID) REFERENCES SCAN_DS (ID) ON
    DELETE
        CASCADE
    ON
    UPDATE
        NO ACTION
    ) COMMENT '数据导入'
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

CREATE TABLE
    SCAN_EXPORTER
    (
        ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编码',
        EXP_NAME VARCHAR(20) NOT NULL COMMENT '名称',
        DESCRIPTION VARCHAR(100) COMMENT '描述',
        PROPS VARCHAR(300) NOT NULL COMMENT '扫描数据源附加属性，为兼容多种数据源',
        DS_ID BIGINT NOT NULL COMMENT '数据源',
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID),
        CONSTRAINT SCAN_EXPORTER_FK1 FOREIGN KEY (DS_ID) REFERENCES SCAN_DS (ID) ON
    DELETE
        CASCADE
    ON
    UPDATE
        NO ACTION
    ) COMMENT '数据导出'
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

CREATE TABLE
    SCAN_TASK
    (
        ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '编码',
        TASK_NAME VARCHAR(20) NOT NULL COMMENT '名称',
        TASK_GROUP VARCHAR(20) NOT NULL COMMENT '分组',
        TASK_TYPE VARCHAR(6) NOT NULL COMMENT '类型: 固定个数线程池fixed/动态增长线程池dynmic',
        TASK_STATE VARCHAR(10) NOT NULL COMMENT '状态:PAUSED/RUNNING',
        DESCRIPTION VARCHAR(100) COMMENT '描述',
        FETCH_SIZE INT NOT NULL COMMENT '每次获取记录的条数',
        SLEEP_TIME INT NOT NULL COMMENT '当获取不到记录时，监听线程休眠时间，单位秒',
        POOL_SIZE INT COMMENT '当类型为fixed时，线程池的大小',
        IMP_ID BIGINT NOT NULL COMMENT '数据导入',
        EXP_ID BIGINT NOT NULL COMMENT '数据导出',
        CTIME DATETIME COMMENT '创建时间',
        PRIMARY KEY (ID),
        CONSTRAINT SCAN_TASK_FK1 FOREIGN KEY (IMP_ID) REFERENCES SCAN_IMPORTER (ID) ON
    DELETE
        RESTRICT
    ON
    UPDATE
        NO ACTION,
        CONSTRAINT SCAN_TASK_FK2 FOREIGN KEY (EXP_ID) REFERENCES SCAN_EXPORTER (ID)
    ON
    DELETE
        RESTRICT
    ON
    UPDATE
        NO ACTION
    ) COMMENT '数据扫描任务'
    ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    